# Dockerfile for the Django service

# The python-onbuild image automatically copies in the files and installs
# the dependencies listed in requirements.txt.
FROM python:3.5-onbuild

# The command to run is listed in the Docker compose file.