# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
                ('level_number', models.IntegerField()),
                ('level_name', models.CharField(max_length=20)),
                ('path_name', models.CharField(max_length=200)),
                ('line_num', models.IntegerField()),
                ('function_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
