# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20160822_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
