# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECCServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('config', models.CharField(max_length=120)),
                ('state', models.IntegerField()),
            ],
        ),
    ]
