# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecc_server_url', models.URLField()),
                ('config', models.CharField(max_length=120)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ECCServer',
        ),
    ]
