# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0003_datasource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='config',
            field=models.CharField(max_length=120, verbose_name='Configuration name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='ecc_server_url',
            field=models.URLField(verbose_name='ECC server URL'),
        ),
    ]
