# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0004_auto_20160602_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
