# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0005_auto_20160603_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=120)),
                ('prepare', models.CharField(max_length=120)),
                ('configure', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_router_url',
            field=models.URLField(default='localhost:1010', verbose_name='Data router URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasource',
            name='state',
            field=models.IntegerField(choices=[(0, 'Idle'), (1, 'Described'), (2, 'Prepared'), (3, 'Configured'), (4, 'Running')], default=0),
        ),
    ]
