# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0006_auto_20160603_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Data router IP address')),
                ('port', models.PositiveIntegerField(verbose_name='Data router port')),
                ('type', models.CharField(choices=[('ICE', 'ICE'), ('TCP', 'TCP'), ('FDT', 'FDT'), ('ZBUF', 'ZBUF')], default='TCP', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ECCServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='ECC server IP address')),
                ('port', models.PositiveIntegerField(default=8083, verbose_name='ECC server port')),
                ('available_configs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daq.ConfigId')),
            ],
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='data_router_url',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='ecc_server_url',
        ),
        migrations.AlterField(
            model_name='datasource',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daq.ConfigId'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_router',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daq.DataRouter'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='ecc_server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daq.ECCServer'),
        ),
    ]
