# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0007_auto_20160603_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eccserver',
            name='available_configs',
        ),
        migrations.AddField(
            model_name='configid',
            name='ecc_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daq.ECCServer'),
        ),
    ]
