# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0008_auto_20160603_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('stop_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='state',
            field=models.IntegerField(choices=[(1, 'Idle'), (2, 'Described'), (3, 'Prepared'), (4, 'Ready'), (5, 'Running')], default=1),
        ),
    ]
