# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0015_auto_20160620_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configid',
            name='last_fetched',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
