# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0017_auto_20160627_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmetadata',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
