# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0019_auto_20160831_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='data_router_log_path',
            field=models.CharField(default='~/Library/Logs/dataRouter.log', max_length=500),
        ),
        migrations.AddField(
            model_name='datasource',
            name='ecc_log_path',
            field=models.CharField(default='~/Library/Logs/getEccSoapServer.log', max_length=500),
        ),
    ]
