# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0020_auto_20160831_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='staging_directory_is_clean',
            field=models.BooleanField(default=True),
        ),
    ]
