# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0021_datasource_staging_directory_is_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='data_router_is_alive',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='ecc_is_alive',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='staging_directory_is_clean',
        ),
        migrations.AddField(
            model_name='datasource',
            name='daq_state',
            field=models.IntegerField(choices=[(0, 'Both dead'), (1, 'Router dead'), (2, 'ECC dead'), (3, 'Ready'), (4, 'Running'), (5, 'Cleaning up')], default=0),
        ),
    ]
