# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0024_auto_20161118_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value_type', models.CharField(choices=[('I', 'Integer'), ('F', 'Float'), ('S', 'String')], max_length=1)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daq.Experiment')),
            ],
        ),
        migrations.AlterModelOptions(
            name='configid',
            options={'ordering': ('describe', 'prepare', 'configure')},
        ),
        migrations.AlterModelOptions(
            name='datarouter',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='eccserver',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='datarouter',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='datarouter',
            name='port',
            field=models.PositiveIntegerField(default=46005),
        ),
        migrations.AlterField(
            model_name='eccserver',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='eccserver',
            name='port',
            field=models.PositiveIntegerField(default=8083),
        ),
        migrations.AddField(
            model_name='measurement',
            name='observable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daq.Observable'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='run_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daq.RunMetadata'),
        ),
    ]
