# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0026_observable_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='observable',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
