# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0027_observable_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmetadata',
            name='config_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runmetadata',
            name='run_class',
            field=models.CharField(choices=[('TEST', 'Testing'), ('PROD', 'Production'), ('BEAM', 'Beam'), ('JUNK', 'Junk'), ('PULS', 'Pulser')], default='PROD', max_length=4),
            preserve_default=False,
        ),
    ]
