# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0029_auto_20161207_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runmetadata',
            name='run_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='runmetadata',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date/time'),
        ),
        migrations.AlterField(
            model_name='runmetadata',
            name='stop_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='stop date/time'),
        ),
    ]
