# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0031_auto_20161209_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='eccserver',
            name='config_root',
            field=models.CharField(default='/Volumes/configs', max_length=500),
        ),
    ]
