# Generated by Django 2.0.13 on 2019-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0002_auto_20190305_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='run_type',
            field=models.IntegerField(null=True),
        ),
    ]
