# Generated by Django 2.0.13 on 2019-03-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0003_log_run_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='run_type',
            field=models.IntegerField(default=-1),
        ),
    ]
