# Generated by Django 2.0.13 on 2019-03-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0004_auto_20190306_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='note',
            field=models.TextField(default='', null=True),
        ),
    ]
