# Generated by Django 2.0.13 on 2019-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0005_auto_20190306_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='d1brho',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='d2brho',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
