# Generated by Django 2.0.13 on 2019-03-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0006_auto_20190307_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='d1brho',
            new_name='fc73',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='d2brho',
            new_name='fc74',
        ),
        migrations.AddField(
            model_name='log',
            name='fc75',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='ic_gas_pressure',
            field=models.FloatField(default=0),
        ),
    ]
