# Generated by Django 2.0.13 on 2019-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0008_auto_20190311_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='scaler1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='scaler2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='scaler3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='scribe',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='trigger_type',
            field=models.IntegerField(default=-1),
        ),
    ]
