# Generated by Django 2.0.13 on 2019-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0009_auto_20190312_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='fc121_begin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fc121_end',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fc122_begin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fc122_end',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fc123_begin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fc123_end',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fc124_begin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fc124_end',
            field=models.FloatField(default=0),
        ),
    ]
