# Generated by Django 2.0.13 on 2019-03-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elog', '0010_auto_20190313_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='fc121_begin',
            new_name='d1_begin',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='fc121_end',
            new_name='d1_end',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='fc122_begin',
            new_name='d2_begin',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='fc122_end',
            new_name='d2_end',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fc123_begin',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fc123_end',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fc124_begin',
        ),
        migrations.RemoveField(
            model_name='log',
            name='fc124_end',
        ),
    ]
