# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0002_auto_20160602_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='name',
            field=models.CharField(default='junk', max_length=50),
            preserve_default=False,
        ),
    ]
