# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0009_auto_20160609_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runmetadata',
            options={'verbose_name': 'run'},
        ),
    ]
