# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0010_auto_20160610_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('target_run_duration', models.PositiveIntegerField(default=3600)),
            ],
        ),
        migrations.AddField(
            model_name='runmetadata',
            name='experiment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='daq.Experiment'),
            preserve_default=False,
        ),
    ]
