# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0012_experiment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='config',
            new_name='selected_config',
        ),
        migrations.RemoveField(
            model_name='configid',
            name='ecc_server',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='ecc_server',
        ),
        migrations.AddField(
            model_name='configid',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daq.DataSource'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='ecc_ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='ECC server IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='ecc_port',
            field=models.PositiveIntegerField(default=8083, verbose_name='ECC server port'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='is_transitioning',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ECCServer',
        ),
    ]
