# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0013_auto_20160613_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='configid',
            name='last_fetched',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 20, 17, 37, 53, 57446)),
            preserve_default=False,
        ),
    ]
