# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0018_runmetadata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='data_router_is_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasource',
            name='ecc_is_alive',
            field=models.BooleanField(default=False),
        ),
    ]
