# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0028_auto_20161207_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runmetadata',
            name='run_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
