# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0032_eccserver_config_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='eccserver',
            name='config_backup_root',
            field=models.CharField(default='~/config_backups', max_length=500),
        ),
    ]
