# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0035_remove_experiment_target_run_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarouter',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daq.Experiment'),
        ),
        migrations.AddField(
            model_name='eccserver',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daq.Experiment'),
        ),
    ]
