# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0037_auto_20170227_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarouter',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daq.Experiment'),
        ),
        migrations.AlterField(
            model_name='eccserver',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daq.Experiment'),
        ),
    ]
