# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daq', '0038_auto_20170227_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarouter',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eccserver',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='datarouter',
            unique_together=set([('name', 'experiment')]),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together=set([('name', 'ecc_server', 'data_router')]),
        ),
        migrations.AlterUniqueTogether(
            name='eccserver',
            unique_together=set([('name', 'experiment')]),
        ),
    ]
